/**
 * MapLibre style for the Hygge Leuven map.
 *
 * Based on OpenFreeMap Positron (https://tiles.openfreemap.org/styles/positron),
 * recolored to match brand tokens against the warm dark background `#3a2a1f`.
 *
 * All label colors WCAG-tested:
 *   `#f4ead8` cream text on `#3a2a1f` background -> contrast ratio ~9.81:1 (AAA)
 *
 * Sources, glyphs, and sprite URLs are preserved unchanged from Positron.
 *
 * NOTE: We avoid a hard dependency on the `maplibre-gl` types package by
 * declaring a minimal structural `StyleSpecification` shape locally. When the
 * style is consumed by `maplibre-gl`'s `Map`, the actual library type is
 * structurally compatible.
 */

import type { StyleSpecification } from "maplibre-gl";

// Brand palette (anchored to design tokens).
const COLORS = {
  background: "#3a2a1f",
  water: "#22160e",
  park: "#4a3a2a",
  buildingFill: "#4d362a",
  buildingOutline: "#2b1d14",
  roadMinor: "#5a4231",
  roadMajor: "#7a5a40",
  motorwayCasing: "#7a3320",
  labelText: "#f4ead8",
  labelHalo: "#2b1d14",
} as const;

const LABEL_PAINT = {
  "text-color": COLORS.labelText,
  "text-halo-color": COLORS.labelHalo,
  "text-halo-width": 1.5,
  "text-halo-blur": 0.5,
} as const;

export const mapStyle: StyleSpecification = {
  version: 8,
  name: "Hygge Leuven (Positron-derived, warm dark)",
  sources: {
    openmaptiles: {
      type: "vector",
      url: "https://tiles.openfreemap.org/planet",
    },
  },
  sprite: "https://tiles.openfreemap.org/sprites/ofm_f384/ofm",
  glyphs: "https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf",
  layers: [
    // ---------- Background ----------
    {
      id: "background",
      type: "background",
      paint: { "background-color": COLORS.background },
    },

    // ---------- Land use / parks / wood ----------
    {
      id: "park",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "park",
      filter: [
        "match",
        ["geometry-type"],
        ["MultiPolygon", "Polygon"],
        true,
        false,
      ],
      paint: { "fill-color": COLORS.park },
    },
    {
      id: "landuse_residential",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landuse",
      maxzoom: 16,
      filter: [
        "all",
        [
          "match",
          ["geometry-type"],
          ["MultiPolygon", "Polygon"],
          true,
          false,
        ],
        ["==", ["get", "class"], "residential"],
      ],
      paint: {
        "fill-color": COLORS.background,
        "fill-opacity": [
          "interpolate",
          ["exponential", 0.6],
          ["zoom"],
          8,
          0.8,
          9,
          0.6,
        ],
      },
    },
    {
      id: "landcover_wood",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landcover",
      minzoom: 10,
      filter: [
        "all",
        [
          "match",
          ["geometry-type"],
          ["MultiPolygon", "Polygon"],
          true,
          false,
        ],
        ["==", ["get", "class"], "wood"],
      ],
      paint: {
        "fill-color": COLORS.park,
        "fill-opacity": [
          "interpolate",
          ["linear"],
          ["zoom"],
          8,
          0,
          12,
          1,
        ],
      },
    },

    // ---------- Water ----------
    {
      id: "water",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "water",
      filter: [
        "all",
        [
          "match",
          ["geometry-type"],
          ["MultiPolygon", "Polygon"],
          true,
          false,
        ],
        ["!=", ["get", "brunnel"], "tunnel"],
      ],
      paint: {
        "fill-antialias": true,
        "fill-color": COLORS.water,
      },
    },
    {
      id: "waterway",
      type: "line",
      source: "openmaptiles",
      "source-layer": "waterway",
      filter: [
        "match",
        ["geometry-type"],
        ["LineString", "MultiLineString"],
        true,
        false,
      ],
      paint: { "line-color": COLORS.water },
    },

    // ---------- Tunnels (minor + motorway under buildings/roads) ----------
    {
      id: "tunnel_motorway_casing",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 6,
      filter: [
        "all",
        [
          "match",
          ["geometry-type"],
          ["LineString", "MultiLineString"],
          true,
          false,
        ],
        [
          "all",
          ["==", ["get", "brunnel"], "tunnel"],
          ["==", ["get", "class"], "motorway"],
        ],
      ],
      layout: { "line-cap": "butt", "line-join": "miter" },
      paint: {
        "line-color": COLORS.roadMinor,
        "line-opacity": 1,
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          5.8,
          0,
          6,
          3,
          20,
          40,
        ],
      },
    },
    {
      id: "tunnel_motorway_inner",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 6,
      filter: [
        "all",
        [
          "match",
          ["geometry-type"],
          ["LineString", "MultiLineString"],
          true,
          false,
        ],
        [
          "all",
          ["==", ["get", "brunnel"], "tunnel"],
          ["==", ["get", "class"], "motorway"],
        ],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": COLORS.roadMinor,
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          4,
          2,
          6,
          1.3,
          20,
          30,
        ],
      },
    },

    // ---------- Building ----------
    {
      id: "building",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "building",
      minzoom: 12,
      paint: {
        "fill-antialias": true,
        "fill-color": COLORS.buildingFill,
        "fill-outline-color": COLORS.buildingOutline,
      },
    },

    // ---------- Roads (minor / path) ----------
    {
      id: "highway_path",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      filter: [
        "all",
        [
          "match",
          ["geometry-type"],
          ["LineString", "MultiLineString"],
          true,
          false,
        ],
        ["==", ["get", "class"], "path"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": COLORS.roadMinor,
        "line-opacity": 0.9,
        "line-width": [
          "interpolate",
          ["exponential", 1.2],
          ["zoom"],
          13,
          1,
          20,
          10,
        ],
      },
    },
    {
      id: "highway_minor",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 8,
      filter: [
        "all",
        [
          "match",
          ["geometry-type"],
          ["LineString", "MultiLineString"],
          true,
          false,
        ],
        [
          "match",
          ["get", "class"],
          ["minor", "service", "track"],
          true,
          false,
        ],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": COLORS.roadMinor,
        "line-opacity": 0.9,
        "line-width": [
          "interpolate",
          ["exponential", 1.55],
          ["zoom"],
          13,
          1.8,
          20,
          20,
        ],
      },
    },

    // ---------- Roads (major: primary / secondary / tertiary / trunk) ----------
    {
      id: "highway_major_casing",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 11,
      filter: [
        "all",
        [
          "match",
          ["geometry-type"],
          ["LineString", "MultiLineString"],
          true,
          false,
        ],
        [
          "match",
          ["get", "class"],
          ["primary", "secondary", "tertiary", "trunk"],
          true,
          false,
        ],
      ],
      layout: { "line-cap": "butt", "line-join": "miter" },
      paint: {
        "line-color": COLORS.buildingOutline,
        "line-dasharray": [12, 0],
        "line-width": [
          "interpolate",
          ["exponential", 1.3],
          ["zoom"],
          10,
          3,
          20,
          23,
        ],
      },
    },
    {
      id: "highway_major_inner",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 11,
      filter: [
        "all",
        [
          "match",
          ["geometry-type"],
          ["LineString", "MultiLineString"],
          true,
          false,
        ],
        [
          "match",
          ["get", "class"],
          ["primary", "secondary", "tertiary", "trunk"],
          true,
          false,
        ],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": COLORS.roadMajor,
        "line-width": [
          "interpolate",
          ["exponential", 1.3],
          ["zoom"],
          10,
          2,
          20,
          20,
        ],
      },
    },
    {
      id: "highway_major_subtle",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      maxzoom: 11,
      filter: [
        "all",
        [
          "match",
          ["geometry-type"],
          ["LineString", "MultiLineString"],
          true,
          false,
        ],
        [
          "match",
          ["get", "class"],
          ["primary", "secondary", "tertiary", "trunk"],
          true,
          false,
        ],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": COLORS.roadMajor,
        "line-width": 2,
      },
    },

    // ---------- Roads (motorway w/ brand accent casing) ----------
    {
      id: "highway_motorway_casing",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 6,
      filter: [
        "all",
        [
          "match",
          ["geometry-type"],
          ["LineString", "MultiLineString"],
          true,
          false,
        ],
        [
          "all",
          [
            "match",
            ["get", "brunnel"],
            ["bridge", "tunnel"],
            false,
            true,
          ],
          ["==", ["get", "class"], "motorway"],
        ],
      ],
      layout: { "line-cap": "butt", "line-join": "miter" },
      paint: {
        "line-color": COLORS.motorwayCasing,
        "line-dasharray": [2, 0],
        "line-opacity": 1,
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          5.8,
          0,
          6,
          3,
          20,
          40,
        ],
      },
    },
    {
      id: "highway_motorway_inner",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 6,
      filter: [
        "all",
        [
          "match",
          ["geometry-type"],
          ["LineString", "MultiLineString"],
          true,
          false,
        ],
        [
          "all",
          [
            "match",
            ["get", "brunnel"],
            ["bridge", "tunnel"],
            false,
            true,
          ],
          ["==", ["get", "class"], "motorway"],
        ],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": COLORS.roadMajor,
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          4,
          2,
          6,
          1.3,
          20,
          30,
        ],
      },
    },
    {
      id: "highway_motorway_subtle",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      maxzoom: 6,
      filter: [
        "all",
        [
          "match",
          ["geometry-type"],
          ["LineString", "MultiLineString"],
          true,
          false,
        ],
        ["==", ["get", "class"], "motorway"],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": COLORS.motorwayCasing,
        "line-opacity": 0.6,
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          4,
          2,
          6,
          1.3,
        ],
      },
    },

    // ---------- Bridges (motorway over rendered above buildings) ----------
    {
      id: "highway_motorway_bridge_casing",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 6,
      filter: [
        "all",
        [
          "match",
          ["geometry-type"],
          ["LineString", "MultiLineString"],
          true,
          false,
        ],
        [
          "all",
          ["==", ["get", "brunnel"], "bridge"],
          ["==", ["get", "class"], "motorway"],
        ],
      ],
      layout: { "line-cap": "butt", "line-join": "miter" },
      paint: {
        "line-color": COLORS.motorwayCasing,
        "line-dasharray": [2, 0],
        "line-opacity": 1,
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          5.8,
          0,
          6,
          5,
          20,
          45,
        ],
      },
    },
    {
      id: "highway_motorway_bridge_inner",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 6,
      filter: [
        "all",
        [
          "match",
          ["geometry-type"],
          ["LineString", "MultiLineString"],
          true,
          false,
        ],
        [
          "all",
          ["==", ["get", "brunnel"], "bridge"],
          ["==", ["get", "class"], "motorway"],
        ],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": COLORS.roadMajor,
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          4,
          2,
          6,
          1.3,
          20,
          30,
        ],
      },
    },

    // ---------- Boundaries ----------
    {
      id: "boundary_3",
      type: "line",
      source: "openmaptiles",
      "source-layer": "boundary",
      minzoom: 8,
      filter: [
        "all",
        [">=", ["get", "admin_level"], 3],
        ["<=", ["get", "admin_level"], 6],
        ["!=", ["get", "maritime"], 1],
        ["!=", ["get", "disputed"], 1],
        ["!", ["has", "claimed_by"]],
      ],
      paint: {
        "line-color": COLORS.roadMinor,
        "line-dasharray": [1, 1],
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          7,
          1,
          11,
          2,
        ],
      },
    },
    {
      id: "boundary_2",
      type: "line",
      source: "openmaptiles",
      "source-layer": "boundary",
      filter: [
        "all",
        ["==", ["get", "admin_level"], 2],
        ["!=", ["get", "maritime"], 1],
        ["!=", ["get", "disputed"], 1],
        ["!", ["has", "claimed_by"]],
      ],
      layout: { "line-cap": "round", "line-join": "round" },
      paint: {
        "line-color": COLORS.roadMajor,
        "line-opacity": [
          "interpolate",
          ["linear"],
          ["zoom"],
          0,
          0.4,
          4,
          1,
        ],
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          3,
          1,
          5,
          1.2,
          12,
          3,
        ],
      },
    },

    // ---------- Labels: water ----------
    {
      id: "water_name_point_label",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "water_name",
      filter: [
        "match",
        ["geometry-type"],
        ["MultiPoint", "Point"],
        true,
        false,
      ],
      layout: {
        "text-field": [
          "case",
          ["has", "name:nonlatin"],
          [
            "concat",
            ["get", "name:latin"],
            "\n",
            ["get", "name:nonlatin"],
          ],
          ["coalesce", ["get", "name_en"], ["get", "name"]],
        ],
        "text-font": ["Noto Sans Italic"],
        "text-letter-spacing": 0.2,
        "text-max-width": 5,
        "text-size": [
          "interpolate",
          ["linear"],
          ["zoom"],
          0,
          10,
          8,
          14,
        ],
      },
      paint: { ...LABEL_PAINT },
    },

    // ---------- Labels: roads ----------
    {
      id: "highway-name-minor",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "transportation_name",
      minzoom: 15,
      filter: [
        "all",
        [
          "match",
          ["geometry-type"],
          ["LineString", "MultiLineString"],
          true,
          false,
        ],
        [
          "match",
          ["get", "class"],
          ["minor", "service", "track"],
          true,
          false,
        ],
      ],
      layout: {
        "symbol-placement": "line",
        "text-field": [
          "case",
          ["has", "name:nonlatin"],
          [
            "concat",
            ["get", "name:latin"],
            " ",
            ["get", "name:nonlatin"],
          ],
          ["coalesce", ["get", "name_en"], ["get", "name"]],
        ],
        "text-font": ["Noto Sans Regular"],
        "text-rotation-alignment": "map",
        "text-size": [
          "interpolate",
          ["linear"],
          ["zoom"],
          13,
          12,
          14,
          13,
        ],
      },
      paint: { ...LABEL_PAINT },
    },
    {
      id: "highway-name-major",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "transportation_name",
      minzoom: 12.2,
      filter: [
        "match",
        ["get", "class"],
        ["primary", "secondary", "tertiary", "trunk"],
        true,
        false,
      ],
      layout: {
        "symbol-placement": "line",
        "text-field": [
          "case",
          ["has", "name:nonlatin"],
          [
            "concat",
            ["get", "name:latin"],
            " ",
            ["get", "name:nonlatin"],
          ],
          ["coalesce", ["get", "name_en"], ["get", "name"]],
        ],
        "text-font": ["Noto Sans Regular"],
        "text-rotation-alignment": "map",
        "text-size": [
          "interpolate",
          ["linear"],
          ["zoom"],
          13,
          12,
          14,
          13,
        ],
      },
      paint: { ...LABEL_PAINT },
    },

    // ---------- Labels: places (suburb / neighbourhood / village / town / city / state / country) ----------
    // Positron does not split out suburb/neighbourhood as separate layers,
    // so we add explicit place_suburb / place_neighbourhood layers here.
    {
      id: "place_suburb",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      minzoom: 11,
      filter: ["==", ["get", "class"], "suburb"],
      layout: {
        "text-field": [
          "case",
          ["has", "name:nonlatin"],
          [
            "concat",
            ["get", "name:latin"],
            "\n",
            ["get", "name:nonlatin"],
          ],
          ["coalesce", ["get", "name_en"], ["get", "name"]],
        ],
        "text-font": ["Noto Sans Italic"],
        "text-letter-spacing": 0.15,
        "text-max-width": 9,
        "text-size": [
          "interpolate",
          ["linear"],
          ["zoom"],
          11,
          10,
          14,
          13,
        ],
        "text-transform": "uppercase",
      },
      paint: { ...LABEL_PAINT },
    },
    {
      id: "place_neighbourhood",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      minzoom: 13,
      filter: ["==", ["get", "class"], "neighbourhood"],
      layout: {
        "text-field": [
          "case",
          ["has", "name:nonlatin"],
          [
            "concat",
            ["get", "name:latin"],
            "\n",
            ["get", "name:nonlatin"],
          ],
          ["coalesce", ["get", "name_en"], ["get", "name"]],
        ],
        "text-font": ["Noto Sans Italic"],
        "text-letter-spacing": 0.1,
        "text-max-width": 9,
        "text-size": [
          "interpolate",
          ["linear"],
          ["zoom"],
          13,
          9,
          16,
          12,
        ],
        "text-transform": "uppercase",
      },
      paint: { ...LABEL_PAINT },
    },
    {
      id: "label_village",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      minzoom: 9,
      filter: ["==", ["get", "class"], "village"],
      layout: {
        "text-anchor": "bottom",
        "text-field": [
          "case",
          ["has", "name:nonlatin"],
          [
            "concat",
            ["get", "name:latin"],
            "\n",
            ["get", "name:nonlatin"],
          ],
          ["coalesce", ["get", "name_en"], ["get", "name"]],
        ],
        "text-font": ["Noto Sans Regular"],
        "text-max-width": 8,
        "text-size": [
          "interpolate",
          ["exponential", 1.2],
          ["zoom"],
          7,
          10,
          11,
          12,
        ],
      },
      paint: { ...LABEL_PAINT },
    },
    {
      id: "label_town",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      minzoom: 6,
      filter: ["==", ["get", "class"], "town"],
      layout: {
        "text-anchor": "bottom",
        "text-field": [
          "case",
          ["has", "name:nonlatin"],
          [
            "concat",
            ["get", "name:latin"],
            "\n",
            ["get", "name:nonlatin"],
          ],
          ["coalesce", ["get", "name_en"], ["get", "name"]],
        ],
        "text-font": ["Noto Sans Regular"],
        "text-max-width": 8,
        "text-size": [
          "interpolate",
          ["exponential", 1.2],
          ["zoom"],
          7,
          12,
          11,
          14,
        ],
      },
      paint: { ...LABEL_PAINT },
    },
    {
      id: "label_state",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      minzoom: 5,
      maxzoom: 8,
      filter: ["==", ["get", "class"], "state"],
      layout: {
        "text-field": [
          "case",
          ["has", "name:nonlatin"],
          [
            "concat",
            ["get", "name:latin"],
            "\n",
            ["get", "name:nonlatin"],
          ],
          ["coalesce", ["get", "name_en"], ["get", "name"]],
        ],
        "text-font": ["Noto Sans Italic"],
        "text-letter-spacing": 0.2,
        "text-max-width": 9,
        "text-size": [
          "interpolate",
          ["linear"],
          ["zoom"],
          5,
          10,
          8,
          14,
        ],
        "text-transform": "uppercase",
      },
      paint: { ...LABEL_PAINT },
    },
    {
      id: "label_city",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      minzoom: 3,
      filter: [
        "all",
        ["==", ["get", "class"], "city"],
        ["!=", ["get", "capital"], 2],
      ],
      layout: {
        "text-anchor": "bottom",
        "text-field": [
          "case",
          ["has", "name:nonlatin"],
          [
            "concat",
            ["get", "name:latin"],
            "\n",
            ["get", "name:nonlatin"],
          ],
          ["coalesce", ["get", "name_en"], ["get", "name"]],
        ],
        "text-font": ["Noto Sans Regular"],
        "text-max-width": 8,
        "text-offset": [0, -0.1],
        "text-size": [
          "interpolate",
          ["exponential", 1.2],
          ["zoom"],
          4,
          11,
          7,
          13,
          11,
          18,
        ],
      },
      paint: { ...LABEL_PAINT },
    },
    {
      id: "label_city_capital",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      minzoom: 3,
      filter: [
        "all",
        ["==", ["get", "class"], "city"],
        ["==", ["get", "capital"], 2],
      ],
      layout: {
        "text-anchor": "bottom",
        "text-field": [
          "case",
          ["has", "name:nonlatin"],
          [
            "concat",
            ["get", "name:latin"],
            "\n",
            ["get", "name:nonlatin"],
          ],
          ["coalesce", ["get", "name_en"], ["get", "name"]],
        ],
        "text-font": ["Noto Sans Bold"],
        "text-max-width": 8,
        "text-offset": [0, -0.2],
        "text-size": [
          "interpolate",
          ["exponential", 1.2],
          ["zoom"],
          4,
          12,
          7,
          14,
          11,
          20,
        ],
      },
      paint: { ...LABEL_PAINT },
    },
    {
      id: "label_country",
      type: "symbol",
      source: "openmaptiles",
      "source-layer": "place",
      maxzoom: 9,
      filter: ["==", ["get", "class"], "country"],
      layout: {
        "text-field": [
          "case",
          ["has", "name:nonlatin"],
          [
            "concat",
            ["get", "name:latin"],
            "\n",
            ["get", "name:nonlatin"],
          ],
          ["coalesce", ["get", "name_en"], ["get", "name"]],
        ],
        "text-font": ["Noto Sans Bold"],
        "text-max-width": 6.25,
        "text-size": [
          "interpolate",
          ["linear"],
          ["zoom"],
          1,
          9,
          5,
          17,
        ],
      },
      paint: { ...LABEL_PAINT },
    },
  ],
};
